###

GET http://localhost:8080/api/qrcodes/[TRAGE HIER EINE ID AUS DER DB EIN]
Accept: application/json

###

GET http://localhost:8080/api/qrcodes/1f92904e-44ed-4e98-8165-2a66afdf2308?cancel=true
Accept: application/json

###

POST http://localhost:8080/api/qrcodes?value=3&no=15&mail=sebi@mail.com
Accept: text/plain

###

GET http://localhost:8080/api/qrcodes?mail=app@mail.com
Accept: application/json

###

GET http://localhost:8080/users/login?login=app&password=app
Content-Type: application/json

###